### ISSUE TITLE
[Craft 3] Unable to register extension as extensions have already been initialised.

### ISSUE THREAD

**Issue by john-henry** [TopShelfCraft/SuperSort#6]
Initial installation of SuperSort on Craft CMS 3.1.12 seemed fine.

Any subsequent update of any _**other**_ plugin generates the following error

```
Status: Internal Server Error

Response: <pre>Exception &#039;LogicException&#039; with message &#039;Unable to register extension &quot;topshelfcraft\supersort\SuperSortTwigExtension&quot; as extensions have already been initialized.&#039;

in ../vendor/twig/twig/lib/Twig/ExtensionSet.php:156

Stack trace:
#0 ../vendor/twig/twig/lib/Twig/Environment.php(672): Twig_ExtensionSet-&gt;addExtension(Object(topshelfcraft\supersort\SuperSortTwigExtension))
#1 ../vendor/craftcms/cms/src/web/View.php(299): Twig_Environment-&gt;addExtension(Object(topshelfcraft\supersort\SuperSortTwigExtension))
#2 ../vendor/topshelfcraft/supersort/src/SuperSort.php(52): craft\web\View-&gt;registerTwigExtension(Object(topshelfcraft\supersort\SuperSortTwigExtension))
#3 ../vendor/yiisoft/yii2/base/BaseObject.php(109): topshelfcraft\supersort\SuperSort-&gt;init()
#4 ../vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject-&gt;__construct(Array)
#5 ../vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module-&gt;__construct(&#039;supersort&#039;, Object(craft\web\Application), Array)
#6 [internal function]: craft\base\Plugin-&gt;__construct(&#039;supersort&#039;, Object(craft\web\Application), Array)
#7 ../vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass-&gt;newInstanceArgs(Array)
#8 ../vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container-&gt;build(&#039;topshelfcraft\\s...&#039;, Array, Array)
#9 ../vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container-&gt;get(&#039;topshelfcraft\\s...&#039;, Array, Array)
#10 ../vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#11 ../vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins-&gt;createPlugin(&#039;supersort&#039;, Array)
#12 ../vendor/craftcms/cms/src/base/ApplicationTrait.php(1223): craft\services\Plugins-&gt;loadPlugins()
#13 ../vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application-&gt;_postInit()
#14 ../vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#15 ../vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct(Array)
#16 ../vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application-&gt;__construct(Array)
#17 [internal function]: craft\web\Application-&gt;__construct(Array)
#18 ../vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass-&gt;newInstanceArgs(Array)
#19 ../vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container-&gt;build(&#039;craft\\web\\Appli...&#039;, Array, Array)
#20 ../vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container-&gt;get(&#039;craft\\web\\Appli...&#039;, Array, Array)
#21 ../vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject(Array)
#22 ../vendor/craftcms/cms/bootstrap/web.php(42): require(&#039;/Users/johnhenr...&#039;)
#23 ../web/index.php(20): require(&#039;/Users/johnhenr...&#039;)
#24 {main}</pre>
```

Maybe related https://github.com/verbb/feed-me/issues/468

I do have Searchit installed

**Comment by john-henry** [comment]
@michaelrog Did you get a chance to review this one?

**Comment by michaelrog** [comment]
🤔 Could have sworn we fixed this one a while ago. What version of SuperSort is installed?

**Comment by john-henry** [comment]
SuperSort  3.0.1

**Comment by michaelrog** [comment]
I suspect some other plugin is hijacking the Twig extension loading process, because in this case the error occurs _before_ SuperSort is actually loaded. (i.e. Another plugin has caused Twig to directly load an extension, rather than going through Craft's API, which prevents any subsequent plugins from loading extensions.)

Marking this Issue as Invalid for now, because there's nothing we can do in SuperSort to resolve it — But please email support@topshelfcraft.com with your dependency list and we'll see if we can help you track down the offending Other Plugin.

(@jalendport 👀 )
